version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-dev
    restart: always
    environment:
      POSTGRES_USER: "devuser"
      POSTGRES_PASSWORD: "devpassword"
      POSTGRES_DB: "habittracker"
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  